server.port=8080
#Spring Data JPA
spring.datasource.url: jdbc:postgresql://dpg-d8no3l8js32c73dtid3g-a:5432/platzi_play_db_9jm7
spring.datasource.username: danieldc
spring.datasource.password: InsLkhNe8tLEQ5UD7V4sXvHESbYwTMnW

spring.jpa.hibernate.ddl-auto=update
#postgresql://danieldc:InsLkhNe8tLEQ5UD7V4sXvHESbYwTMnW@dpg-d8no3l8js32c73dtid3g-a.oregon-postgres.render.com/platzi_play_db_9jm7

langchain4j.open-ai.chat-model.api-key=demo
spring.sql.init.mode=always